### ISSUE TITLE
usage of color extension does not exist in readme file

### ISSUE THREAD

**Issue by goranjovanov1910** [goranjovanov1910/Useful_SwiftExtensions#4]
Can't find the usage of color extension.

**Comment by goranjovanov1910** [comment]
@yuriipinchuk 
Could you update readme for the color extension?

**Comment by yuriipinchuk** [comment]
@goranjovanov1910 
Issue is resolved in https://github.com/goranjovanov1910/Useful-SwiftExtensions/pull/5
